package uc.eecs.nlp;

import java.util.Arrays;import java.util.List;public class StopWords {
    public static List<String> STOP =
            Arrays.asList(
                    "javax",
                    "impl",
                    "ecf",
                    "ui",
                    "java",
                    "apache",
                    "org",
                    "you",
                    "i",
                    "they",
                    "set",
                    "need",
                    "should",
                    "remy",
                    "container", "debug",
                    "provider",
                    "can", "run", "project", "jdt", "io", "example", "classpath", "access", "util", "tomcat", "synchronize",
                    "not",
                    "method",
                    "problem", "come", "visit", "jar",
                    "master","osgi", "handle", "stop",
                    "application",
                    "difficult",
                    "see",
                    "version",
                    "app",
                    "tid",
                    "nid",
                    "second",
                    "workspace",
                    "dump",
                    "attach",
                    "like",
                    "quick",
                    "jdwp",
                    "implementation",
                    "jdi",
                    "jmdns",
                    "feel",
                    "shutdown",
                    "object",
                    "make",
                    "seem",
                    "guess",
                    "find",
                    "exception",
                    "bug",
                    "string",
                    "but",
                    "return",
                    "notice",
                    "hello",
                    "scheme",
                    "branch",
                    "cause",
                    "period",
                    "use",
                    "time",
                    "become",
                    "own",
                    "wait",
                    "api",
                    "code",
                    "have",
                    "list",
                    "thread",
                    "important",
                    "eclipse",
                    "detail",
                    "improve");
}
